# Generated by Django 5.2 on 2025-04-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='source_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
