# Generated by Django 5.2 on 2025-04-27 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_meal_recipe_ingredient_alter_meal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_recipe',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient'),
        ),
        migrations.AlterField(
            model_name='meal_recipe',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.recipe'),
        ),
    ]
