# Generated by Django 4.1.7 on 2025-04-20 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
